[package]
name = "mv-mqtt-client"
version = "0.0.1"
authors = ["Jonas Greitemann <jgreitemann@gmail.com>"]
edition = "2018"
autobins = false

[dependencies]
gio = "0.9.1"
glib = "0.10.3"
gtk = "0.9.2"
enum-map = "0.6.4"
itertools = "0.10.0"
futures = "0.3.8"
paho-mqtt = "0.9.0"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"

[lib]
name = "mvjson"
path = "src/mvjson/lib.rs"

[[bin]]
name = "mv_mqtt_client"
path = "src/bin/main.rs"
