name: Flatpak

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flatpak:
    name: "Build Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-42
      options: --privileged
    steps:
      - uses: actions/checkout@v3

      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: mv-mqtt-client.flatpak
          manifest-path: io.github.jgreitemann.mv-mqtt-client.yml
          cache-key: flatpak-builder-${{ github.sha }}